blank_issues_enabled: false
contact_links:
  - name: OpenTelemetry Community
    url: https://github.com/open-telemetry/community
    about: For general OpenTelemetry community discussions and governance
  - name: OpenTelemetry Documentation
    url: https://opentelemetry.io/docs/
    about: For questions about OpenTelemetry documentation and usage